name: Call Bitrise build API

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      workflow:
        required: true
        type: string
    outputs:
      response:
        description: "The response of Bitrise API"
        value: ${{ jobs.build.outputs.response }}
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BITRISE_SLUG: '9acd23037a1e0480'
    outputs:
      response: ${{ steps.call.outputs.response }}
    steps:
      - name: Call Bitrise build API
        id: call
        run: |
          response=$(curl -X POST "https://api.bitrise.io/v0.1/apps/${BITRISE_SLUG}/builds" -H "accept: application/json" -H "Authorization: ${{ secrets.token }}" -H "Content-Type: application/json" -d "{ \"build_params\": { \"branch\": \"${{ inputs.branch }}\", \"workflow_id\": \"${{ inputs.workflow }}\" }, \"hook_info\": { \"type\": \"bitrise\" }}")
          echo '${response}' | jq .
          echo "response=${response}" >> $GITHUB_OUTPUT
