name: Start DeployGate build

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: 'Configuration'
        required: true
        default: 'inhouse'
        type: choice
        options:
        - inhouse
        - staging

jobs:
  build:
    uses: ./.github/workflows/call-bitrise-api.yml
    with:
      branch: ${{ github.ref_name }}
      workflow: ${{ inputs.configuration }}
    secrets: 
      token: ${{ secrets.BITRISE_TOKEN }}
