name: Dispatch

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Build type'
        required: true
        default: 'inhouse'
        type: choice
        options:
        - inhouse
        - staging
        - release

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: "print"
        env:
          TYPE: ${{ inputs.type }}
          BRANCH: ${GITHUB_REF}
        run: |
          echo "TYPE: $TYPE"
          echo "BRANCH: $BRANCH"
  build:
    uses: ./.github/workflows/call-bitrise-api.yml
    with:
      branch: ${GITHUB_REF}
      type: ${{ inputs.type }}
    secrets: 
      slug: ${{ secrets.BITRISE_SLUG }}
      token: ${{ secrets.BITRISE_TOKEN }}
