name: QA-build-request

on:
  pull_request:
    types: [labeled, synchronize] # ラベル追加 or Pull Request更新

jobs:
  build:
    # 追加されたラベルが'QA'のとき or 'QA'ラベルが付いたPull Requestに変更が加わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    uses: ./.github/workflows/call-circleci-api.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      build_flavor: 'staging'
      build_type: 'proguardDebug'
    secrets: 
      token: ${{ secrets.CIRCLE_TOKEN }}

  comment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      # Bitrise APIの実行結果をPull Requestにコメントする
      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'QAビルド依頼 実行結果\n```\n${{ needs.build.outputs.build_url }}\n```',
            });
