name: Bitrise

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  staging-build:
    # 'QA'ラベルが追加されたとき or 'QA'ラベルが付いたPull Requestに新たなcommitが追加されたとき or 'QA'ラベルが付いたPull Requestのbase branchが変わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    runs-on: ubuntu-latest
    steps:
      # Bitrise APIを叩く
      - name: Call bitrise API
        id: call_bitrise_api
        env:
          BITRISE_SLUG: ${{ secrets.BITRISE_SLUG }}
          BITRISE_TOKEN: ${{ secrets.BITRISE_TOKEN }}
        run: |
          echo "${{ github.event_name }}"
          echo "name=${{ github.event_name }}" >> $GITHUB_OUTPUT
      
      # Bitrise APIの実行結果をPull Requestにコメントする
      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ steps.call_bitrise_api.outputs.result }}',
            });
