name: CI

on:
  pull_request:
    types: labeled

jobs:
  add-comment:
    if: github.event.label.name == 'QA'
    runs-on: ubuntu-latest
    steps:
      - name: 'Get information of the pull request'
        id: pull_request_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.pull_request.url }})
          echo "::set-output name=head_branch::$(echo ${RESPONSE} | jq '.head.ref' | sed 's/\"//g')"
      - name: Post comment
        if: success()
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "対象の branch は ${{ steps.pull_request_info.outputs.head_branch }} です"
            });
