name: Bitrise

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  staging-build:
    # 'QA'ラベルが追加されたとき or 'QA'ラベルが付いたPull Requestに新たなcommitが追加されたとき or 'QA'ラベルが付いたPull Requestのbase branchが変わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    uses: ./.github/workflows/call-bitrise-api.yml
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      type: "staging"
      slug: ${{ secrets.BITRISE_SLUG }}
    secrets: 
      token: ${{ secrets.BITRISE_TOKEN }}

  post-comment:
    runs-on: ubuntu-latest
    needs: [staging-build]
    steps:
      # Bitrise APIの実行結果をPull Requestにコメントする
      - name: Post comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ needs.staging-build.outputs.response }}',
            });
