name: CI

on:
  pull_request:
    types: labeled

jobs:
  add-comment:
    if: github.event.label.name == 'QA'
    runs-on: ubuntu-latest
    steps:
      - name: 'Post comment'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo ${{ github.event }};
