name: Bitrise

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  staging-build:
    # 'QA'ラベルが追加されたとき or 'QA'ラベルが付いたPull Requestに新たなcommitが追加されたとき or 'QA'ラベルが付いたPull Requestのbase branchが変わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    runs-on: ubuntu-latest
    steps:
      # scriptを実行する
      - name: Execute script
        id: execute_script
        env:
          BITRISE_SLUG: ${{ secrets.BITRISE_SLUG }}
          BITRISE_TOKEN: ${{ secrets.BITRISE_TOKEN }}
        run: |
          sh ./bin/script.sh
#          echo "::set-output name=result::$(curl -X POST "https://api.bitrise.io/v0.1/apps/${BITRISE_SLUG}/builds" -H "accept: application/json" -H "Authorization: ${BITRISE_TOKEN}" -H "Content-Type: application/json" -d "{ \"build_params\": { \"branch\": \"${{ github.event.pull_request.head.ref }}\", \"workflow_id\": \"staging\" }, \"hook_info\": { \"type\": \"bitrise\" }}")"
      
      # Bitrise APIの実行結果をPull Requestにコメントする
#      - name: Post comment
#        uses: actions/github-script@v3
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            github.issues.createComment({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              issue_number: context.issue.number,
#              body: '${{ github.event.action }}',
#            });
