name: Bitrise

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  staging-build:
    # 'QA'ラベルが追加されたとき or 'QA'ラベルが付いたPull Requestに新たなcommitが追加されたとき or 'QA'ラベルが付いたPull Requestのbase branchが変わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    runs-on: ubuntu-latest
    steps:
      # checkoutする
      - name: Checkout
        uses: actions/checkout@v3

      # scriptを実行する
      - name: Execute script
        id: execute_script
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          echo "::set-output name=result::$(curl --header "Content-Type: application/json" --data '{"build_parameters": {"BUILD_FLAVOR": "'$build_flavor'", "BUILD_TYPE": "'$build_type'"}}' --request POST https://circleci.com/api/v1.1/project/github/tdrk18/BitBox/tree/$revision?circle-token=$CIRCLE_TOKEN)"
      
      # 実行結果をPull Requestにコメントする
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ steps.execute_script.outputs.result }}',
            });
