name: Bitrise

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  staging-build:
    # 'QA'ラベルが追加されたとき or 'QA'ラベルが付いたPull Requestに新たなcommitが追加されたとき or 'QA'ラベルが付いたPull Requestのbase branchが変わったとき
    if: github.event.label.name == 'QA' || (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'QA'))
    runs-on: ubuntu-latest
    steps:
      # checkoutする
      - name: Checkout
        uses: actions/checkout@v3

      # scriptを実行する
      - name: Execute script
        id: execute_script
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          echo "::set-output name=result::$(CIRCLE_TOKEN=CIRCLE_TOKEN sh ./bin/script.sh staging proguardDebug ${{ github.event.pull_request.head.ref }})"
      
      # 実行結果をPull Requestにコメントする
      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '${{ github.event.action }}',
            });
